### ISSUE TITLE
Checkout without payment?

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#14]
From what I can tell at this point, the primary concerns I have are the ability to delete products is not working and I know you're working on that bug.  And then the checkout process which is a biggie.

Will the checkout process have the option to NOT pay anything?  Peshtigo Nat'l Bank wants to handle all of the money through payroll deduction.  So they're asking if we can collect orders through this store, but then I'd separately invoice PNB for the grand total.  Then internally they are going to cover part of the cost and collect the rest from the employees through payroll deduction.  The only thing I'd ideally get from this store would be the ability to run a report that shows me all of their sales over a certain time period with a grand total due.  

They have a company meeting on 2/15 which they want to announce some sort of update regarding this store.  Doesn't mean it has to be ready to start,, but ideally they'd love an estimated date of when it would be ready by and then maybe they'd roll it out in March or April?   I'm confident you'll be able to solve the "delete product" issue but I am nervous about checkout.

**Comment by smitdalt** [comment]
I could add an option per store to not bill individually, but still track orders.

I could see issues arising from this, though, as all verification that the buyer is actually from the company is lost. Before, the individual at least had to pay for the item, but now nothing would be stopping anyone from going to the Peshtigo store and creating a bunch of fake orders because the payment step would be bypassed.

One way around this could be to require some sort of verification code that is given to employees that they need to enter to create orders for the store. It isn't the most secure option, but it is much better than allowing anyone to create orders on the store.

**Comment by karentooley** [comment]
I like the "verification code" idea!
